.github/workflows/test.yml
demos/2d_compressible_ALA/Makefile
demos/2d_compressible_TALA/Makefile
demos/2d_cylindrical/Makefile
demos/3d_cartesian/Makefile
demos/3d_spherical/Makefile
demos/Drucker-Prager_rheology/Makefile
demos/adjoint/Makefile
demos/analytical_comparisons/Makefile
demos/base_case/Makefile
demos/optimisation_checkpointing/Makefile
demos/viscoplastic_case/Makefile

The dualspace-aware fixes for pyadjoint have been merged, so we can already unpin pyadjoint for our testing container. As another line of defense in diagnosis, the testing makefiles print out how long each of the runs took.

Testing fixes (unpin pyadjoint, add timing)

---

demos/analytical_comparisons/delta_cylindrical_freeslip.py
demos/analytical_comparisons/delta_cylindrical_freeslip_dpc.py
demos/analytical_comparisons/delta_cylindrical_zeroslip.py
demos/analytical_comparisons/delta_cylindrical_zeroslip_dpc.py
demos/analytical_comparisons/smooth_cylindrical_freeslip.py
demos/analytical_comparisons/smooth_cylindrical_zeroslip.py

Slacken solver tolerances marginally for analytical cases. This (for my testing at least!) seems to reduce the number of inner solve failures, and in the long-term should improve stability of the tests. I wonder if some of this has contributed to the timing issues @stephankramer has been seeing. I'll dig deeper tomorrow.

Lower tolerances, to avoid the occasional inner solve failure.

---

gadopt/approximations.py

I was reading through `approximations.py` and discovered the concept of an abstract base class. However, I think there is an issue with how it is currently implemented. From what I read, the `@abc.abstractmethod` decorator is only useful if the method it targets belongs to a class that is derived from `abc.ABCMeta`. Indeed, in the current implementation, one could write
```python
from gadopt.approximations import BaseApproximation
class Foo(BaseApproximation):
pass
a = Foo()
```
and no error would be raised.

Enforce implementation of abstract methods

---

.github/workflows/test.yml

If the testing workflow has already been triggered on a pull request, updates to that pull request should now cause the existing test to be cancelled. This means we don't have to wait or manually cancel outdated runs.

Cancel in-progress CI runs on PR update

---

demos/adjoint_2d_cylindrical/forward.py
demos/adjoint_2d_cylindrical/inverse.py

This PR fixes an inconsistency in defining the strain-rate for non-linear cases. The definition of `forward.py` currently uses an additional factor of $\sqrt{1/2}$, that should actually appear in the definition for `epsii`. 
To make the two scripts consistent, and also the same as the original scripts for running the adoints we are now using a higher `sigma_y`.

Fix adoint cylindrical

---

gadopt/stokes_integrators.py

Do as the title says! I have found with a number of test cases that this improves solver behaviour at all levels (reduces the number of inner solve iterations). Would like to run through test suite as an independent change, to ensure I didn't miss anything, prior to merging.

Change GAMG default to use mis_k_minimum_degree_ordering

---

.github/workflows/lint.yml
.github/workflows/longtest.yml
.github/workflows/test.yml
Makefile
demos/Makefile
demos/adjoint/cases.py
demos/adjoint/taylor_test.py
demos/adjoint/test_adjoint.py
demos/adjoint_2d_cylindrical/cases.py
demos/adjoint_2d_cylindrical/taylor_test.py
demos/adjoint_2d_cylindrical/test_cylindrical_adjoint.py
demos/analytical_comparisons/Makefile
demos/analytical_comparisons/analytical.py
demos/analytical_comparisons/run_gadi.sh
demos/analytical_comparisons/smooth_spherical_freeslip.py
demos/analytical_comparisons/smooth_spherical_zeroslip.py
demos/analytical_comparisons/test_analytical.py
pytest.ini

This finally adds the more expensive spherical analytical cases, as well as the testing framework that will let us fire off automated tests on HPC (just Gadi for the moment).
- maybe do this on the remote machine too, by adding a pytest tag for longtest results? the SSH command will error if pytest fails

Add spherical analytical with long test framework

---

.github/workflows/test.yml

These now show up on the workflow summary page, rather than needing to go into the run log itself.

Create workflow summaries for test status and timings

---

demos/optimisation_checkpointing/helmholtz.py
demos/optimisation_checkpointing/test_checkpointing.py
gadopt/inverse.py

This PR changes the default iteration for the restored checkpoint to be the last stored checkpoint instead of requiring a given iteration number to restore from.
Note that if a user adds other subdirectories to `checkpoint_dir` then this might/will break as it assumes the only things in there are the subdirectories for the iterations' checkpoints. I think this is a non-issue as we probably don't need to allow for that?

Change default restored checkpoint in optimisation to the last saved

---

demos/2d_cylindrical/2d_cylindrical.py
gadopt/preconditioners.py

The mass matrix we use as an approximation of the Schur complement does not actually have a nullspace, so when we use cg to invert it in order to apply it as a preconditioner, we should not be removing the nullspace inside the cg iteration. This in fact led to frequent (silently failing) solves - add ['fieldsplit_1']['Mp_ksp_converged_reason'] = None to see - either failing with definite pc, or (worse) failing to converge within 10000 iterations. The latter is of course a bit of time waste (the pressure mass cg iteration is rel. fairly cheap, so not as bad as you might think). The fact that this solve (silently) fails also didn't seem to impact the overall convergence of the Schur complement (outer iteration).
Note that this only leaves out the nullspace in the pressure mass solve …

Don't remove nullspace inside massinvpc solve.

---

gadopt/inverse.py

This fixes the checkpointing iteration counter for restored optimisations.
Currently, the restored iteration gets saved again in the checkpointing directory as the next iteration. So after restoring from say iteration 10, this gets checkpointed as iteration 11 but is still iteration 10 as far as ROL is concerned. This means that with each restored run of the optimisation the directory names in the checkpoint directory and the actual ROL iteration values get more and more out of sync.
Please let me know if this was intended behaviour, but doesn't seem very user-friendly to me!

Fix the iteration counter for restored optimiser

---

.github/workflows/test.yml
requirements-git.txt

With some recent changes (including moving our working branch of pyrol to master), the Ubuntu-provided CMake isn't sufficiently new enough (even though none of the new features are actually used :roll_eyes:). This change only affects the case when the pyrol wheel is rebuilt, i.e. when it isn't cached, so it shouldn't hit every invocation of the workflow.

Install updated CMake image when building pyrol wheel for Actions

---

demos/2d_compressible_ALA/compressible_case_ALA.py
demos/2d_compressible_TALA/compressible_case_TALA.py
demos/2d_cylindrical/2d_cylindrical.py
demos/3d_cartesian/3d_cartesian.py
demos/3d_spherical/3d_spherical.py
demos/adjoint/forward.py
demos/adjoint/inverse.py
demos/adjoint/taylor_test.py
demos/base_case/base_case.py
gadopt/stokes_integrators.py

In many of demos, as well as some simplified Earth-like problems, we do  not have time-varying viscosity. For example for our adjoint optimisations, we might do many iterations with only a depth dependent viscosity to obtain a better "initial guess", before considering temperature-(or other temporally changing) dependencies. Currently we do assume the LHS of the stokes problem needs to be updated every timestep, whereas in the aforementioned cases this is not the case, as the Jacobian needs to be assembled once. 
With this PR, if `constant_jacobian=True` is provided to `StokesSolver` we setup a `LinearVariationalProblem` with `constant_jacobian=True`, which should result in considerable speed up in run-time for cases with temporally constant viscosities.

Informing `StokesSolver` when our LHS is not changing in time. 

---

.github/workflows/test.yml
pyproject.toml

Now that this is being built for most platforms, we should use the packaged wheel to make sure that's working, and remove the need for a fairly lengthy build in the testing workflow. This should also make things simpler for upstream installs (i.e. `pip install gadopt[optimisation]` should do what you want).
I've also split the gadopt specification: installing bare gadopt **won't** include pyrol, or assess/pandas. These packages are pulled in by the *optimisation* and *testing* variants, respectively. So in the installation for testing, we now install `gadopt[testing,optimisation]`. Is this a sensible way to split things up?

Defer to PyPI for pyroltrilinos package

---

gadopt/diagnostics.py
gadopt/utility.py

This PR changes the way interpolation is used for LayerAveraging and Adaptive time-stepping to be consistent with future Firedrake changes and avoid raising long weird warnings.

Changing Interpolators to be consistent with future Firedrake changes

---

CITATION.cff
README.md
get_software_citation.py

Based on Angus' repo:
https://github.com/angus-g/lagrangian-filtering/blob/master/CITATION.cff
need a zenodo doi for g-adopt (adjoint paper zenodo points to the wrong link...!)

Add citation to github page

---

demos/Drucker-Prager_rheology/spiegelman.py
gadopt/__init__.py
gadopt/preconditioners.py
gadopt/stokes_integrators.py

The main reason to have our own version of MassInvPC was that MassInvPC did not update for varying (between solves) viscosities. This has been fixed in https://github.com/firedrakeproject/firedrake/pull/3372 and since then the options structure for the solvers beneath it has changed: need to use pcksp with an additional ksp_ layer now. Thus VariableMassInvPC is no longer a drop in-replacement for MassInvPC as it was intended. Better to stay consistent with Firedrake therefore.

Remove VariableMassInvPC

---

gadopt/stokes_integrators.py
tests/test_stokes_solver_configuration.py

Default iterative and direct Stokes solver parameters can now be specified using eponymous strings.

Use string to request default solver parameters

---

demos/2d_compressible_ALA/compressible_case_ALA.py
demos/2d_compressible_TALA/compressible_case_TALA.py
demos/3d_cartesian/3d_cartesian.py
demos/3d_spherical/3d_spherical.py
demos/base_case/base_case.py
demos/viscoplastic_case/viscoplastic_case.py
gadopt/diagnostics.py

Instead of splitting our mixed function `z` and then passing `u` and `p` around (e.g. to `GeodynamicalDiagnostics`), it seems to make more sense to provide it with `z` directly. We have precedent for this already in `StokesSolver`, especially with the free surface fields coming in #51.
Additionally, instead of exposing some of the gory MPI internals in our demos, I've pushed that into a `ux_max` diagnostic, which can be given a surface ID. I think related to the discussion in #74, this would be better off knowing what the "lateral" direction is, as it just makes the cartesian assumption at the moment.

Convert GeodynamicalDiagnostics to accept a mixed function

---

demos/.diagram.mermaid

I've already put a `.pages` file in the demos directory that is used for the table of contents that shows up on the documentation site. I think that, and this diagram make more sense here because they can be updated alongside the demos.
Diagram is rendered here: https://10f9be33.g-adopt.pages.dev/tutorials/
Also has links to the tutorials that show up in the hierarchy, plus adjoint on the side (without a link until #80 goes in).

Add diagram showing relationship of demos

---

gadopt/utility.py
tests/unit/test_interpolate_1d_profile.py

Currently the following code fails because of [this issue](https://github.com/firedrakeproject/firedrake/issues/3652) from tsfc: 
```python3
from gadopt.utility import vertical_component
from gadopt import *
mesh2d = CubedSphereMesh(1, refinement_level=1, degree=2)
mesh = ExtrudedMesh(mesh2d, layers=2, extrusion_type='radial')
Q = FunctionSpace(mesh, "CG", 1)  # Temperature function space (scalar)
upward_component = vertical_component(SpatialCoordinate(mesh), cartesian=False)
q = Function(Q, name="r")
q.interpolate(upward_component)
```
The change just rewrites the UFL for the two inner products.

A fix for vertical_component and upward_normal in 3d extruded meshes.

---

demos/2d_compressible_ALA/Makefile
demos/2d_compressible_TALA/Makefile

There's some kind of parallel ordering bug with the MUMPS+METIS combo for direct solves that seems to pop up in particular on these test cases. Using a different solver (e.g. SuperLU_DIST) avoids this issue. The other option would be PaStiX, but it segfaults on the compressible demos. We can't enable superlu globally, because that affects convergence on one of our tests, causing the CI to time out (see https://github.com/g-adopt/g-adopt/actions/runs/9900787219/job/27352140174). To avoid modifying the demo directly, we perform the solver override only when running the demo in its test configuration.

Force SuperLU_DIST on compressible demos

---

.github/workflows/render.yml

Instead of rendering the demo notebooks as part of the website build, it makes more sense to render them in this repository, and provide the rendered results as artifacts.
As a first stage, this just adds the workflow to master so it can trigger. Then we can enable the dispatch on the website side, and then finally we can turn on the automatic dispatch here!

Add render workflow

---

.github/workflows/render.yml

Follows on from #96, now that the required changes are in place on the website side.

Trigger documentation build after notebook render

---

.github/workflows/render.yml
demos/.pages

The awesome-pages plugin interacts badly with the mkdocs material blog, so we'll switch to literate-nav which requires this format instead.

Change format of demo table of contents

---

.github/workflows/render.yml
demos/3d_spherical/3d_spherical.py
demos/gplates_global/gplates_global.py

There are a few irrelevant warnings in our tutorials (an import warning from Firedrake, interpolation, plotting, etc.) that we can improve upon. There is one outstanding warning from the gplates demo:
```
/home/firedrake/firedrake/lib/python3.12/site-packages/gadopt/gplates/gplates.py:407: RuntimeWarning: Issues finding plate ids for some of the seeds.
warnings.warn("Issues finding plate ids for some of the seeds.", category=RuntimeWarning)
```
I think this can go up as an issue for @sghelichkhani to address later.

Address warnings in tutorials

---

demos/adjoint/adjoint.py

Reopening https://github.com/g-adopt/g-adopt/pull/107, since reverting my commit automatically closed the PR. 
This is now fixing timestep=80.

Fixing a minor issue with adjoint demo

---

.github/workflows/render.yml

Of course the upstream action changed this without bumping the version, breaking our workflow...

Include hidden files in render pipeline

---

.github/workflows/lint.yml
.github/workflows/test.yml

Just a small maintenance; it should fix a CI [warning](https://github.com/g-adopt/g-adopt/actions/runs/11103281454) regarding Node.js versions.

Update action versions

---

.github/workflows/longtest.yml

We also skip the unit test directory, since pytest collection will fail when trying to import Firedrake in some of the tests.

Fix pytest directory for longtest

---

Makefile
demos/2d_compressible_ALA/Makefile
demos/2d_compressible_TALA/Makefile
demos/2d_cylindrical/Makefile
demos/3d_cartesian/Makefile
demos/3d_spherical/Makefile
demos/Makefile
demos/base_case/Makefile
demos/free_surface/Makefile
demos/gplates_global/Makefile
demos/multi_material/Makefile
demos/test_all.py
demos/viscoplastic_case/Makefile
pytest.ini
tests/2d_cylindrical_TALA_DG/Makefile
tests/Drucker-Prager_rheology/Makefile
tests/Makefile
tests/adjoint/Makefile
tests/analytical_comparisons/Makefile
tests/analytical_comparisons/analytical.py
tests/analytical_comparisons/test_analytical.py
tests/free_surface/Makefile
tests/multi_material/Makefile
tests/optimisation_checkpointing/Makefile
tests/parallel_scaling/Makefile
tests/scalar_advection_diffusion/Makefile
tests/viscoplastic_case_dg/Makefile

Revamp makefiles. make check now runs appropriate tests wherever its invoked. Top level behaviour remains the same, make check in demos only tests demos, make check in an individual test only tests that, etc. Most make check invocations depend on test output. Some tests were modified to make this work properly. make clean now removes all artefacts from testing.

Makefile cleanup

---

.github/workflows/render.yml

Sometimes we want to run a documentation render without updating the website, to check that it would complete. To support this, we add a "trigger" input to the workflow dispatch for this action.

Make triggering a documentation rebuild optional

---

demos/Makefile

jupytext calls nbconvert to use its ExecutePreprocessor which starts a NotebookClient which starts a KernelManager through a LocalProvisioner. Of course, KernelManager includes a ConnectionFileMixin and tries to bind 5 random ports when it provisions the manager, then writes this to a file for when the Client actually starts. This is a big race condition, and means that the automatic retry code in the Client for random ports never gets hit, because the port is already specified in the connection file.
The solution herein isn't foolproof, but barring a big hang in the initialisation of jupyter it should work. We serialise just the startup of the render jobs through a lockfile which gives each process 1 second to start before releasing the lock.
Closes #143.

Serialise startup of render jobs

---

.github/workflows/render.yml
.testing/jupytext
demos/Makefile

This is possibly a less hacky alternative to #147 for ensuring all the jupyter kernels don't run into each other when they try to bind ports on startup.
There are plusses and minuses to this approach. The environment needs to be more carefully set up so that the namespace works, including setting subuid and subgid. I think it's probably also the case that the render jobs won't have external network access without setting up a veth device in the namespace. Maybe that's not the worst thing -- we get a fairly robust guarantee that we don't have any network dependencies.
Actions run: https://github.com/g-adopt/g-adopt/actions/runs/11848173592

Run render jobs with namespaced networking

---

gadopt/inverse.py
tests/optimisation_checkpointing/Makefile
tests/optimisation_checkpointing/helmholtz.py
tests/optimisation_checkpointing/test_checkpointing.py

Mistaken change in 30a3388 (Use comm-free UUID for optimisation checkpointing) broke parallel compatibility of optimisation checkpointing. Of course, the checkpoints for the ROL vectors need to be collective, so they all need to write to the same file with the same ID. We can go back to Firedrake's _get_uid, and just use the communicator associated with the function on the vector.

Generate optimisation checkpoints with collective ID

---

.github/workflows/test.yml

I had originally made the runlogs upload when the tests step fails, but for some reason this was always temperamental. Let's instead just upload an artifact containing all the runlogs, regardless of test status. This should make it much easier to dig into failing tests.
An example of this is when I unpinned the Firedrake image leading to TSFC errors: https://github.com/g-adopt/g-adopt/actions/runs/11789097245

Upload all run logs for tests

---

tests/analytical_comparisons/delta_cylindrical_freeslip.py
tests/analytical_comparisons/delta_cylindrical_freeslip_dpc.py
tests/analytical_comparisons/delta_cylindrical_zeroslip.py
tests/analytical_comparisons/delta_cylindrical_zeroslip_dpc.py
tests/analytical_comparisons/smooth_cylindrical_freeslip.py
tests/analytical_comparisons/smooth_cylindrical_freesurface.py
tests/analytical_comparisons/smooth_cylindrical_zeroslip.py
tests/analytical_comparisons/smooth_spherical_freeslip.py
tests/analytical_comparisons/smooth_spherical_zeroslip.py
tests/parallel_scaling/stokes_cubed_sphere.py

In few of the tests we are still using `interpolate` as a stand-alone function for the `assemble(interpolate(*))` behaviour. This will get rid of the warnings.

Changing interpolate in tests

---

gadopt/time_stepper.py
tests/free_surface/explicit_free_surface.py

Time integrators in `time_stepper.py` accept two arguments that are not used: `bnd_conditions` and `terms_to_add`. This PR removes these extraneous arguments.

Remove unused arguments in `time_stepper.py`

---

gadopt/level_set_tools.py
gadopt/time_stepper.py
gadopt/transport_solver.py
tests/free_surface/explicit_free_surface.py
tests/multi_material/run_benchmark.py

The current argument order in `TimeIntegratorBase.advance` and `RungeKuttaTimeIntegrator.advance` is not ideal. `t` is a required argument, whilst `update_forcings` is an optional argument. However, `t` is only used as an argument to `update_forcings`, which breaks the previous logic. In other words, passing `t` currently without providing `update_forcings` has no impact, as can be seen from `tests/free_surface/explicit_free_surface.py`. Here, the argument order is swapped, and both arguments become optional.

Swap argument order in timestepper advance method

---

demos/generate_expected.py

While working on the level-set API changes, I updated pickle files for expected values. It was frustrating that `generate_expected.py` would silently do nothing if the demo path I passed as a command argument contained a trailing slash. The proposed changes here should ensure this does not happen anymore.

Update `generate_expected.py` to allow trailing slash

---

gadopt/transport_solver.py
tests/scalar_advection/scalar_advection.py
tests/scalar_advection_diffusion/scalar_advection_diffusion.py
tests/scalar_advection_diffusion/scalar_advection_diffusion_DH219_skew.py
tests/scalar_advection_diffusion/scalar_advection_diffusion_DH27.py

PR #114 changed the api to allow users to specify an ```su_diffusivity``` This is maybe confusing because if a 'real' background diffusivity is given then we should use this diffusivity used to calculate the grid peclet number for the su advection scheme.
In the case where there is no diffusion term we just set kappa=0 since we already have a hack to specify a (hopefully) small 1e-12 value for the diffusivity anyway.

Change su_diffusivity back to an on/off flag

---

.github/workflows/longtest.yml
tests/analytical_comparisons/Makefile
tests/analytical_comparisons/run_gadi.sh
tests/analytical_comparisons/smooth_cylindrical_freesurface.py
tests/base_gmsh/Makefile
tests/base_gmsh/test_base_case.py
tests/parallel_scaling/Makefile
tests/parallel_scaling/run_gadi.sh
tests/parallel_scaling/scaling.py
tests/parallel_scaling/test_scaling.py

Works fine, just had to change that iteration component name to get it to work. I was going to put the `module use`, `module load` steps in `run_gadi.sh`, but I changed my mind as its a good idea to have that separate to the repository so that we can test new firedrake branches as well. Location and usage of `$GADOPT_SETUP` would be good to add to our hypothetical internal docs page.

Use firedrake modules on Gadi for longtest

---

gadopt/inverse.py
tests/optimisation_checkpointing/helmholtz.py

Should fix an error when checkpointing is enabled after restarting a checkpointed optimisation.

Set comm on restored CheckpointedROLVector

---

.github/workflows/test.yml

The Firedrake container now runs as root by default, which makes git complain about safe directories. Set all directories as safe, remove the `$HOME` hack (because Firedrake was installed to `$HOME/.local`, now in `/opt`) and install tsp directly into `/usr/local`. Hopefully gets CI running again...

Adapt to Firedrake root containers

---

tests/Drucker-Prager_rheology/test_spiegelman.py

The conf dictionary is always copied before modification, so it doesn't need to be global in the test scope. Will fix our newly developed lint failure.

Remove unnecessary global scope from test_spiegelman

---

.github/workflows/test.yml
rules.mk

Added 'timeout' functionality to `tsp`. Now we don't need to wrap the tests in the `timeout` command. It shouldn't do anything in this run. However, here are my results from an earlier test with the timeout set to 3 minutes.
<details><summary>Details</summary>
```
[dr4292@gadi-cpu-spr-0284 ~]$ TMPDIR=/jobfs/138322102.gadi-pbs/ tsp --list
ID  |      State | ExitStat |   Run Time |    Command
=====================================================
1       finished          0      1:37.418  python3 base_case.py
2       finished        143      3:06.660  python3 implicit_top_bottom_free_surface.py
3       finished          1      1:01.225  python3 gplates_global.py
4       finished          0      1:40.567  python3 compositional_buoyancy.py
5       finished        143      3:06.841  python3 …
```

Modify tests to use tsp --timeout function

---

gadopt/stokes_integrators.py

This PR contains the first set of changes transitioning the current Stokes integrators module towards the one proposed in gh-158. The end goal is to inherit solver classes from an abstract base class, and the methods defined here will become part of the abstract base class.

Pack boundary conditions and solver options in `StokesSolver` methods

---

tests/unit/data/solver_params.py
tests/unit/test_solver_parameters.py

In response to a recent Firedrake regression where solver parameters weren't being passed through to blocks on the tape. This is a bit brute force, but we ensure that our artificial "gadopt_test" option is processed by the options database when we play the tape forward by evaluating the reduced functional.
I think maybe the implementation here is a bit ugly and certainly happy to take a different approach!

Add unit test for solver parameter consistency

---

.github/workflows/render.yml
pyproject.toml

There were a couple of outdated constructs in the render workflow that don't apply with the Firedrake root container. The real issue here is that I _think_ we need to explicitly specify that we have a `gadopt.gplates` subpackage, because we're not using setuptools' automatic package discovery. It's kind of weird that this only sometimes shows up on the render job, and it doesn't ever cause an issue on the testing job. I think this should probably wait for (or be combined with) #213 so that we don't get spurious test failures.

Fix render workflow

---

gadopt/gplates/gplates.py

Diffusion is a constant that is used in non-dimensionalising time, and velocities when using pygplates Connector. This PR allows setting kappa. The default value is kept 1.0 so that we not need an interface change or any other change to demos.

Diffusion Constant in pygplates connector

---

gadopt/inverse.py

The "Safeguard Size" and "Gradient Tolerance" parameters that are present in the minimisation defaults are actually floats, but they are written as ints. With a default build of ROL using boost::property_list, this doesn't cause any issues. However, it's possible to build ROL using Teuchos to manage the parameter lists, and it'll complain about type issues.

Use correct type for optimisation parameters

---

demos/mantle_convection/free_surface/free_surface.py
gadopt/approximations.py
gadopt/equations.py
gadopt/preconditioners.py
gadopt/stokes_integrators.py
tests/free_surface/implicit_cylindrical_free_surface.py
tests/free_surface/implicit_free_surface.py
tests/free_surface/implicit_top_bottom_free_surface.py

This PR attempts to streamline the free surface implementation in `StokesSolver`. In doing so, it introduces two new methods (`set_equations` and `set_form`) that deal with setting up `Equation` instances and calculating the weak form based on the theta scheme.

Update free surface setup in `StokesSolver` using new `set_equations` and `set_form` methods

---

demos/multi_material/thermochemical_buoyancy/thermochemical_buoyancy.py

Just a quick fix for the failing demo build. See https://github.com/g-adopt/g-adopt/actions/runs/15436764247 for passing demo run with this branch.

Add missing import to thermochemical demo

---

pyproject.toml

We can unpin when https://github.com/pyvista/pyvista/issues/7587 is closed (which should be pretty soon really). Should allow render jobs to complete again.

Pin VTK for pyvista compatibility

---

gadopt/utility.py
tests/unit/test_boundary_detection.py

Correct axis convention to z is depth for non-extruded 3D meshes in `get_boundary_ids`. Correct this in `test_boundary_detection` as well. Update paths to `mesh.geo` files in the `multi_material` tests.
Closes #253.

Fix `get_boundary_ids` and `test_boundary_detection`

---

gadopt/equations.py
gadopt/level_set_tools.py
gadopt/stokes_integrators.py

A few changes/improvements I had to make/spotted whilst looking at a 3-D level-set simulation. 
- `cell_edge_integral_ratio` is missing `hexahedron`. I checked the document linked in the docstring and concluded `hexahedron` probably falls in the same category as `quadrilateral * interval`. Moreover, I rewrote the function's logic using `match/case` and converted the error message to an f-string to make things look cleaner.
-  `gradient_space` in `set_gradient_solver` should be defined on `CG` to allow for both simplex and quad support.
- `ls_data` in `min_max_height` needs to be clipped away from 0.0 and 1.0 to avoid issues in `numpy.log` calls. Such issues are likely to arise for coarser meshes (and unreasonable interface-thickness values).
- `geometric_dimension` in …

Code improvements/fixes identified whilst testing 3-D level set

---

gadopt/level_set_tools.py

`material_entrainment` is currently restricted to "Cartesian" meshes. It is only a simple change to allow non-Cartesian compatibility, as shown here. I tested and validated the updated functionality on a multi-material version of the 2D cylindrical demo.

Allow material entrainment calculation on "non-Cartesian" meshes

---

gadopt/limiter.py
tests/unit/test_continuity.py
tests/unit/test_extrusion_tools.py
tests/unit/test_limiters.py

Current unit-test execution produces warnings, namely:
- `UserWarning: Discontinuous Lagrange element requested on quadrilateral, creating DQ element.`
- `UserWarning: Discontinuous Lagrange element requested on interval * interval, creating DQ element.`
- `FutureWarning: The use of 'interpolate' to perform the numerical interpolation is deprecated.`
- `UserWarning: PyOP2.Global has no comm, this is likely to break in parallel!`
This PR proposes changes to prevent warning occurrences.

Fix warnings produced through unit tests

---

gadopt/stokes_integrators.py

Fixes an issue with removing the average value of dynamic topography.  Before the surface area was wrongly being calculated using ds(mesh), which gives the total surface of the mesh, whereas we are only interested in the specific `subdomain_id`. 
We now provide the mesh to `self.ds` so that surface area integral would work simply with `self.ds`.

Fixing the surface integral for dynamic topography average

---

.github/workflows/longtest.yml

Allow longtest to run on different systems simultaneously. Do not cancel workflow if longtest on one system fails.

Fix longtest concurrency

---

.github/workflows/render.yml
demos/Makefile

It could also be useful to use the "skip-execution" tag on these cells, so they can have stub/invalid code in them. I've written a bit of documentation, including these tags [on the wiki](https://github.com/g-adopt/g-adopt/wiki/Writing-tutorials).
Closes #248

Remove "exercise" tags from rendered output

---

tests/analytical_comparisons/analytical.py
tests/analytical_comparisons/test_analytical.py

These don't converge so well at the lower grid refinements, but the behaviour is still correct. Extending to level 7, both cases are displaying the expected convergence:
Free slip:
l2error_u  l2error_p  l2error_sigma
1   3.990554   1.863376       1.776315
2   3.938721   1.975899       1.956374
3   3.915053   1.993982       1.990689
4   3.894285   1.998381       1.998217
Zero slip:
l2error_u  l2error_p  l2error_sigma
1   4.073229   1.823242       1.789542
2   3.914674   1.970972       1.958939
3   3.887527   1.993600       1.990625
4   3.886618   1.998406       1.997803
Instead of making the test accept values from 1.75-2.01, we can drop level 3 and accept values from 1.9 to 2.1, which should hopefully make it easier to spot issues. This way we'll hopefully be back to green on the HPC …

Remove level 3 from spherical analytical cases

---

tests/parallel_scaling/test_scaling.py

The level 5 parallel scaling tests run on less than a full node, so can be scheduled across a single CPU, or across multiple CPUs. This leads to the level 5 tests having a much more variable runtime than the level 6 or 7 tests.

Increase tolerance on level 5 parallel scaling test

---

gadopt/utility.py

Needed for https://github.com/firedrakeproject/firedrake/pull/4531. The `Interpolator` is intended for internal use only. The symbolic `interpolate` function should be used instead.

replace `Interpolator` with `interpolate`

---

demos/glacial_isostatic_adjustment/2d_cylindrical/2d_cylindrical.py
demos/mantle_convection/2d_cylindrical/2d_cylindrical.py
demos/mantle_convection/dynamic_topography/dynamic_topography.py
gadopt/stokes_integrators.py
tests/2d_cylindrical_TALA_DG/2d_cylindrical_TALA_DG.py
tests/adjoint_2d_cylindrical/forward.py
tests/adjoint_2d_cylindrical/inverse.py
tests/analytical_comparisons/delta_cylindrical_freeslip.py
tests/analytical_comparisons/delta_cylindrical_freeslip_dpc.py
tests/analytical_comparisons/delta_cylindrical_zeroslip.py
tests/analytical_comparisons/delta_cylindrical_zeroslip_dpc.py
tests/analytical_comparisons/smooth_cylindrical_freeslip.py
tests/analytical_comparisons/smooth_cylindrical_freesurface.py
tests/analytical_comparisons/smooth_cylindrical_zeroslip.py
tests/unit/test_stokes_solver_configuration.py

To have a consistent behaviour between transport and Stokes solvers, this PR enforces direct solver parameters for all 2-D simulations. Existing demos and tests that relied on an iterative solver now explicitly specify this need.
Closes #125

Make direct solver parameters the default for 2-D simulations

---

demos/PDE_constrained_optimisation/PDE_constrained_boundary.py
demos/PDE_constrained_optimisation/PDE_constrained_field.py
tests/unit/test_adjoints.py

For testing and visualisation, we want to be dealing with the primal derivative quantity (the gradient), so we need to explicitly apply the Riesz representation. This is the API change due to the `AbstractReducedFunctional` in pyadjoint.

Request Riesz representation on derivative calls
