- demos/analytical_comparisons/Makefile
- demos/analytical_comparisons/analytical.py
- demos/analytical_comparisons/delta_cylindrical_freeslip_dpc.py
- demos/analytical_comparisons/delta_cylindrical_zeroslip.py
- demos/analytical_comparisons/delta_cylindrical_zeroslip_dpc.py
- demos/analytical_comparisons/smooth_cylindrical_zeroslip.py
- demos/analytical_comparisons/test_analytical.py
- gadopt/equations.py
Add final analytical examples in a cylindrical domain. I will add spherical examples in a separate pull request.
> Add all analytical examples

- gadopt/energy_solver.py
- gadopt/time_stepper.py
This is to be consistent with Stokes solver and allows users to override parameters setup at initialisation.
> Defer setup of timestepper+solver for energy equation

- gadopt/energy_solver.py
> Fix direct solver options for energy equation

- demos/2d_cylindrical/2d_cylindrical.py
- demos/3d_spherical/3d_spherical.py
This will be removed, currently raising a FutureWarning. Hopefully this is the right way to do things?
> Convert Constants with domains to Functions

- demos/Drucker-Prager_rheology/Makefile
- demos/Drucker-Prager_rheology/spiegelman.py
- demos/Drucker-Prager_rheology/test_spiegelman.py
- demos/Makefile
This one has been sitting for a while, but it's based on the same idea as the analytical cases -- the test script will spit out the parameter configurations to run, and then it will check that they converge as expected.
> Add testing to Spiegelman cases

- demos/adjoint/inverse.py
This PR introduces a vertical masking function to  allow damping only within thermal boundary layers.
> Damping mask

- .github/workflows/longtest.yml
- README.md
- requirements-git.txt
- requirements.txt
Just a few little things:
- remove the `requirements.txt` and `requirements-git.txt` files, now that the dependencies are handled directly by the package
- fix the longtest workflow due to the addition of unit tests
- small tweak to the readme
> Minor housekeeping tweaks

- gadopt/approximations.py
- gadopt/diagnostics.py
- gadopt/energy_solver.py
- gadopt/equations.py
- gadopt/inverse.py
- gadopt/limiter.py
- gadopt/momentum_equation.py
- gadopt/preconditioners.py
- gadopt/scalar_equation.py
- gadopt/stokes_integrators.py
- gadopt/time_stepper.py
- gadopt/utility.py
- setup.cfg
Given the current effort to revamp the G-ADOPT website, this PR attempts to improve the codebase documentation. Comments and suggestions are welcome!
> DOC: Add and harmonise docstrings and type annotations

- demos/2d_compressible_ALA/compressible_case_ALA.py
- demos/2d_compressible_TALA/compressible_case_TALA.py
- demos/2d_cylindrical/2d_cylindrical.py
- demos/3d_cartesian/3d_cartesian.py
- demos/3d_spherical/3d_spherical.py
- demos/Drucker-Prager_rheology/spiegelman.py
- demos/adjoint/forward.py
- demos/adjoint_2d_cylindrical/forward.py
- demos/analytical_comparisons/delta_cylindrical_freeslip.py
- demos/analytical_comparisons/delta_cylindrical_freeslip_dpc.py
- demos/analytical_comparisons/delta_cylindrical_zeroslip.py
- demos/analytical_comparisons/delta_cylindrical_zeroslip_dpc.py
- demos/analytical_comparisons/smooth_cylindrical_freeslip.py
- demos/analytical_comparisons/smooth_cylindrical_zeroslip.py
- demos/analytical_comparisons/smooth_spherical_freeslip.py
- demos/analytical_comparisons/smooth_spherical_zeroslip.py
- demos/base_case/base_case.py
- demos/scalar_advection/scalar_advection.py
- demos/scalar_advection_diffusion/scalar_advection_diffusion.py
- demos/scalar_advection_diffusion/scalar_advection_diffusion_DH219_skew.py
- demos/scalar_advection_diffusion/scalar_advection_diffusion_DH27.py
- demos/viscoplastic_case/viscoplastic_case.py
- gadopt/__init__.py
- pyproject.toml
Following the recent changes in Firedrake ([PR #3324](https://github.com/firedrakeproject/firedrake/pull/3324)), where `vtk` has been made an optional dependency, this pull request aims to update gadopt accordingly. Given that all our demos rely on `vtk` for visualisations, it's crucial for our package to explicitly require `vtk` to ensure a seamless user experience. Consequently, this PR:
- Adds `vtk` as a mandatory dependency in `pyproject.toml` to guarantee its installation with `gadopt`.
- Replaces instances of `File` with `VTKFile` across the codebase.
> Update to Firedrake VTKFile interface

- gadopt/energy_solver.py
Closes gh-62
Pretty much self-explanatory; see the linked issue for additional detail.
> Prevent use of SU advection with discontinuous function spaces

- demos/analytical_comparisons/delta_cylindrical_freeslip.py
- demos/analytical_comparisons/delta_cylindrical_freeslip_dpc.py
- demos/analytical_comparisons/delta_cylindrical_zeroslip.py
- demos/analytical_comparisons/delta_cylindrical_zeroslip_dpc.py
- demos/analytical_comparisons/smooth_cylindrical_freeslip.py
- demos/analytical_comparisons/smooth_cylindrical_zeroslip.py
- demos/analytical_comparisons/smooth_spherical_freeslip.py
- demos/analytical_comparisons/smooth_spherical_zeroslip.py
Just for testing purposes. Are smooth analytical benchmark comparisons sensitive to dx?
> Use default dx in analytical cases

- gadopt/utility.py
`interpolate_1d_profile` relies on `numpy.interp` for one-dimensional interpolation. However, it currently does not check if the user-provided data is strictly monotonous and if it is given in increasing order. These missing checks can produce silently meaningless results.
> Ensure strictly increasing data for interp

- gadopt/scalar_equation.py
Putting up a pull request mainly to determine if this breaks anything else (although admittedly we don't currently test for DG extensively, so suspect all will be ok!).
> Test fix to solution of DG energy equation, under compressible approximations

- demos/.diagram.mermaid
- demos/.pages
- demos/2d_compressible_ALA/2d_compressible_ALA.py
- demos/2d_compressible_TALA/2d_compressible_TALA.py
> Re-order ALA and TALA demos

- demos/gplates_global/gplates_global.py
- gadopt/gplates/__init__.py
- gadopt/gplates/gplates.py
- gadopt/gplates/gplatesfiles.py
- tests/unit/test_gplates.py
Obvious from the title, this will provide access to different versions of the plate reconstruction model Muller et al 2022.
> Allow for more generic configuration of plate reconstruction datasets

- .github/workflows/longtest.yml
- tests/analytical_comparisons/analytical.py
- tests/analytical_comparisons/smooth_cylindrical_freesurface.py
> Make sure long free surface test runs

- tests/2d_cylindrical_TALA_DG/2d_cylindrical_TALA_DG.py
- tests/2d_cylindrical_TALA_DG/Makefile
Fixing what I believe was forgotten in gh-124. Let us see what the CI returns.
> Use default solver tolerances in TALA DG

- demos/mantle_convection/viscoplastic_case/viscoplastic_case.py
From the workshop, it's more useful to see the logarithm of viscosity. Since UFL only supports the natural log, we do $ln(x)/ln(10)$.
> Plot log(mu) at end of viscoplastic demo

- demos/glacial_isostatic_adjustment/2d_cylindrical/2d_cylindrical.py
- demos/glacial_isostatic_adjustment/base_case/base_case.py
- demos/mantle_convection/gplates_global/gplates_global.py
> Make GIA demos consistent with Mantle and tidy up GPlates case a little

- .github/workflows/render.yml
- .github/workflows/test.yml
- gadopt/limiter.py
- gadopt/utility.py
Solves https://github.com/g-adopt/g-adopt/issues/135
> Unpin Firedrake image for CI

- .github/workflows/render.yml
- .github/workflows/test.yml
Now that we have the exciting new package, let's test it out. I hope I haven't missed anything. I think we just use it in the render and test workflows.
> Install pygplates from PyPI

- gadopt/stokes_integrators.py
> subfunctions renamed to subspaces for FunctionSpace

- .github/workflows/render.yml
- .github/workflows/test.yml
> Switch CI to use Firedrake pip install

- tests/analytical_comparisons/Makefile
We (I) had been pointing at the old module files, oops!
> Correct storage flags on analytical longtest run

- .github/workflows/test.yml
- pyproject.toml
Maybe this makes sense?
Closes #234.
> Run our own smoke tests

- .github/workflows/memprof_plot.yml
More or less the same as "Trigger documentation build" step in render.yml.
> Trigger github_status rebuild when new memory profiling plots are created

- gadopt/level_set_tools.py
Just a few final touches that were missed in previous PRs. Hopefully, nothing contentious.
Any further PR modifying this file should only address compatibility issues with non-Cartesian and 3-D geometries.
> Final minor improvements to `level_set_tools.py`

- tests/analytical_comparisons/smooth_cylindrical_freesurface.py
This test fails to converge on Setonix with the existing settings.
> Loosen tolerance in smooth_cylindrical_freesurface

- .github/workflows/render.yml
- .github/workflows/test.yml
This commit should allow PRs from forks to run in our CI by removing the need to access any repository secrets.
> Download plate reconstructions with curl

- tests/viscoelastic/zhong_viscoelastic_free_surface.py
> Fix viscoelastic test (don't convert R space back to constant) 
